package com.example.quizdesing;
    public class PerguntasRespostas {
        public static String[] perguntas = {
                "Em que ano foi criado o filme Vingadores: A era de Ultron?",
                "Em qual filme do MCU Wanda Maximoff aparece pela primeira vez?",
                "EM QUAL ANO FOI LANÇADO O PRIMEIRO FILME DO MCU?",
                "THOR RAGNAROK FOI LANÇADO EM QUAL ANO ?",
                "Que ator é conhecido pelo seu papel como O Hulk?",
                "Qual é o nome do martelo encantado do Thor?",
                "De qual monumento o Peter Parker salva seus colegas de escola em Homem-Aranha: De Volta ao Lar?",
                "Quantas Joias do Infinito existem?",
                "Qual é o nome do projeto de super soldado em Capitão América: O Primeiro Vingador?",
                "Qual é o nome do vilão do primeiro filme de “Homem-Formiga ?",
                "Em que filme o Thanos aparece pela primeira vez?",
                "Como Wakanda adquire o vibrânio?",
                "A Viúva Negra é originalmente de qual país?",
                "Como o Nick Fury perdeu o olho?",
                "Antes de Tom Holland pegar o papel do Homem-Aranha, quantos outros atores interpretaram o papel no cinema?",
                "Qual é o filme final da fase 1 da Marvel?",
                "Peggy Carter é recrutada por Howard Stark para ajudar a comandar a versão inicial da S.H.I.E.L.D. Qual produção mostra isso?",
                "Loki morre nos braços de Thor. Em que projeto isso acontece?",
                "Qual desses filmes teve a primeira aparição de um Celestial, a raça mais antiga do universo?",
                "Para evitar descontroles do Gigante Esmeralda, o Hulk abandona a Terra. Quando isso acontece?",
                "Do que é feito o escudo do Capitão América?",
                "Antes de se tornar Vision, qual é o nome do mordomo de IA do Homem de Ferro?",
                "Qual é o verdadeiro nome da Pantera Negra?",
                "Qual é a raça alienígena que Loki envia para invadir a Terra em Os Vingadores?",
                "Quem foi o último detentor do Pedra do espaço antes de Thanos reivindicá-lo por sua Manopla do Infinito?",
                "Qual o nome do asa noturna?",
                "Quem criou a DC?",
                "Qual foi o primeiro herói da DC?",
                "Quem é o pior inimigo do Batman?",
                "Superman é de qual planeta?",
                "Quem é o lanterna amarelo?",
                "Quem foi o primeiro Robin?",
                "Quem é a prima do superman ?",
                "Como super choque consegue seus poderes?",
                "Qual é o primeiro herói que Batman pediu ajuda?",
                "Qual o nome dos pais de Batman?",
                "Qual era o emprego do coringa antes de enlouquecer?",
                "O Alfred ajuda qual super herói?",
                "Qual a fraqueza do marciano?",
                "Ravena e filha de quem?",
                "Quem e o exterminador?",
                "Qual o nome verdadeiro do superboy? ",
                "O que significa DC comics?",
                "Quem é o mais rápido da DC?",
                "Quem matou shazam? ",
                "Quem é o maior vilão do superman?",
                "O bizarro é o que do superman?",
                "Como um lanterna verde é escolhido?",
                "Qual o verdadeiro nome do superman?",
                "O que Billy Batson faz para se tornar Shazam"
        };

        public static String[][] respostas = {
                {"2015", "2016", "2014","2017"},
                {"GUERRA INFINITA", "TERCEIRO ATO DO FILME HOMEM-FORMIGA", "CENA PÓS CRÉDITOS DE CAPITÃO AMÉRICA O SOLDADO INVERNAL", "A ERA DE ULTRON"},
                {"2011", "2008", "2007", "2010"},
                {"2018", "2017", "2016", "2009"},
                {"VINCENT D’ONOFRIO", "NOAH CENTINEO", "MARK WAHLBERG", "MARK RUFFALO"},
                {"MJÖLNIR", "MNAJAS", "GUNGNIRS", "ASGARD"},
                {"BIG BEN ", "TORRE EIFFEL", "MONUMENTO DE WASHINGTON", "ESTÁTUA DA LIBERDADE"},
                {"3", "6","9","12"},
                {"PROJETO RENASCIMENTO", "PROJETO RENOVAÇÃO", "PROJETO RESTAURAÇÃO", "PROJETO REAVIVAMENTO "},
                {"VESPA", "ABELHA", "JAQUETA AMARELA", "FORMIGA PRETA "},
                {"HOMEM DE FERRO", "GUADIÕES DA GALÁXIA", "VINGADORES ULTIMATO", "OS VINGADORES"},
                {"VEIO EM FORMA DE ASTEROIDE", "FOI ENCONTRADO NATURALMENTE NO SOLO", "VEIO DE UMAS DAS JOIAS DO INFINITO", "FOI INVOCADO ATRAVÉS DA MAGIA"},
                {"TCHECOSLOVAQUIA", "RUSSIA", "POLONIA ", "EUA"},
                {"TIRO NO OLHO", "ARRANHÃO DE UM GATO", "PERDEU EM UMA BATALHA SANGRENTA", "NASCEU CEGO DE UM OLHO"},
                {"3", "5","2","4"},
                {"HOMEM DE FERRO", "OS VINGADORES", "DOUTOR ESTRANHO", "PANTERA NEGRA"},
                {"CAPITÃO AMÉRICA: O PRIMEIRO VINGADOR", "WHAT IF", "CURTA MARVEL: AGENTE CARTER", "AGENTE CARTER"},
                {"THOR: O MUNDO SOMBRIO", "THOR: RAGNAROK", "LOKI (SERIE DE TV)", "THOR AMOR E TROVÃO"},
                {"ETERNOS", "GUARDIÕES DA GALÁXIA VOL: 2", "GUARDIÕES DA GALÁXIA", "THOR: O MUNDO SOMBRIO"},
                {"THOR RAGNAROK", "VINGADORES ERA DE ULTRON", "CAPITÃO AMÉRICA: GUERRA CIVIL", "VINGADORES"},
                {"Adamantium", "vibranium", "promécio", "Carbonádio"},
                {"HOMER", "JARVIS", "ALFRED", "MARVIN"},
                {"T’CHALLA", "M'Baku", "N'Jadaka", "N'Jobu"},
                {"Os Chitauri", "Os skrulls", "O Kree", "Os Flerkens"},
                {"Thor", "Loki", "O Colecionador", "Tony Stark"},
                {"Damian Wayne ", "Bruce Wayne", "jason Todd", "Dick Grayson"},
                {"Stan Lee", "Aaron Horvtah", "Malcom Wheeler", "Gardner Fox"},
                {"superman", "Batman", "Shazam", "Canário Negro"},
                {"Coringa", "Bane", "Charada", "Crocodilo"},
                {"marte", "Tamaran", "Krypton", "Apokilips"},
                {"Kyle rayner", "Guy Gardner", "John Stewart", "Sinestro"},
                {"Damian Wayne", "B - Jason Todd", "Dick Grayson", "Tim Drake"},
                {"supergirl", "Estellar", "Ravena", "Super Lady"},
                {"cobaia em experimento", "Exposto a gas mutagenico", "Experimento com enguias elétricas", "Atingido por um raio "},
                {"Mulher maravilhan", "Aquaman", "Flash", "Mutano"},
                {"Stepan Wayne e Laura Wayne", "Martin Wayne e Martha Wayne", "Tobias Wayne e Marcia Wayne", "Thomas  Wayne e Martha Wayne"},
                {"Palhaço de circo", "Comediante", "cantor", "Assassino de aluguel"},
                {"Superman", "Shazam", "Batman", "Mulher Maravilha"},
                {"Sol", "Gelo", "Flores", "Fogo"},
                {"Trigon", "Cavaleiro negro", "Ares", "Hades"},
                {"Drax Wilson", "jason Todd", "Dick Grayson", "Slade Wilson"},
                {"Lex Conner", "Conner kent", "Clark Kent", "Hand Kent"},
                {"Destreza Comics", "Detetive Columbia", "Detective Comics", "Descrição cosmica"},
                {"Flash", "Savitar", "superman", "Kid Flash"},
                {"Batman", "Adão negro", "Superman", "Superboy"},
                {"Metallo", "Apocalypse", "homem brinquedo", "Lex luthor"},
                {"Clone", "Uma Versão paralela", "Irmão", "Alucinação"},
                {"Força de vontade", "pela coragem", "por experiencia", "pela bondade"},
                {"Kal-el", "Clark Kent", "Hal jordan", "Jor-el"},
                {"ele se torna Shazam quando morre", "Gritando Shazam", "Absorvendo a energia solar", "Quando fica com raiva"}
        };

        public static String[] respostas_corretas = {
                "2015",
                "CENA PÓS CRÉDITOS DE CAPITÃO AMÉRICA O SOLDADO INVERNAL",
                "2008",
                "2017",
                "MARK RUFFALO",
                "MJÖLNIR",
                "MONUMENTO DE WASHINGTON",
                "6",
                "PROJETO RENASCIMENTO",
                "JAQUETA AMARELA",
                "OS VINGADORES",
                "VEIO EM FORMA DE ASTEROIDE",
                "RUSSIA",
                "ARRANHÃO DE UM GATO",
                "2",
                "OS VINGADORES",
                "CURTA MARVEL: AGENTE CARTER",
                "THOR: O MUNDO SOMBRIO",
                "GUARDIÕES DA GALÁXIA",
                "VINGADORES ERA DE ULTRON",
                "vibraniun",
                "JARVIS",
                "T’CHALLA",
                "OS CHITAURI",
                "LOKI",
                "Dick Grayson",
                "Malcom Wheeler",
                "Superman",
                "Coringa",
                "Krypton",
                "Sinestro",
                "Dick Grayson",
                "Supergirl",
                "Exposto a gás mutagenico",
                "Aquaman",
                "Thomas  Wayne e Martha Wayne",
                "Comediante",
                "Batman",
                "Fogo",
                "Trigon",
                "Slade Wilson",
                "Conner kent",
                "Detective Comics",
                "Flash",
                "Superman",
                "Lex luthor",
                "Uma Versão paralela",
                "Força de vontade",
                "Kal-el",
                "Gritando Shazam"
        };
    }


